# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logRPA.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("border-radus: 5px;")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_erro = QtWidgets.QFrame(self.top_bar)
        self.frame_erro.setMaximumSize(QtCore.QSize(500, 40))
        self.frame_erro.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"border-radius:5px;\n"
"")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_erro = QtWidgets.QLabel(self.frame_erro)
        self.label_erro.setStyleSheet("QLabel{\n"
"     color:rgb(35, 35, 35);\n"
"}\n"
"")
        self.label_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_3.addWidget(self.label_erro)
        self.pushButton_cluse_pupup = QtWidgets.QPushButton(self.frame_erro)
        self.pushButton_cluse_pupup.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_cluse_pupup.setStyleSheet("QPushButton{\n"
"    background-image: url(:/close image/icon_close.png);\n"
"    border-raius: 5px;\n"
"    margin: 0px 0px 0px 0px ;\n"
"    background-position: center;    \n"
"    background-color: rgb(70, 70, 70);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(40,40,40);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QpushButton:pressed{\n"
"    background-color: rgb(35,35,35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.pushButton_cluse_pupup.setText("")
        self.pushButton_cluse_pupup.setObjectName("pushButton_cluse_pupup")
        self.horizontalLayout_3.addWidget(self.pushButton_cluse_pupup)
        self.horizontalLayout_2.addWidget(self.frame_erro)
        self.verticalLayout.addWidget(self.top_bar)
        self.context = QtWidgets.QFrame(self.centralwidget)
        self.context.setStyleSheet("")
        self.context.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.context.setFrameShadow(QtWidgets.QFrame.Raised)
        self.context.setObjectName("context")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.context)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login = QtWidgets.QFrame(self.context)
        self.login.setMaximumSize(QtCore.QSize(450, 550))
        self.login.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 10px;\n"
"border: 3px solid rgb(177, 185, 249);\n"
"")
        self.login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.login)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame.setStyleSheet("border: rgba(0,0,246,100)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 30, 141, 131))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.login)
        self.frame_2.setStyleSheet("border: rgba(0,0,246,100)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_user.setGeometry(QtCore.QRect(80, 20, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radiius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100,100,100);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(77,77,77);    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(177, 185, 249);    \n"
"    color: rgb(200,200,200);\n"
"}")
        self.lineEdit_user.setMaxLength(10)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_user_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_user_2.setGeometry(QtCore.QRect(80, 80, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_user_2.setFont(font)
        self.lineEdit_user_2.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radiius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(100,100,100);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(77,77,77);    \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(177, 185, 249);    \n"
"    color: rgb(200,200,200);\n"
"}")
        self.lineEdit_user_2.setMaxLength(16)
        self.lineEdit_user_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_user_2.setObjectName("lineEdit_user_2")
        self.checkBox_saveuser = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_saveuser.setGeometry(QtCore.QRect(80, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.checkBox_saveuser.setFont(font)
        self.checkBox_saveuser.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(100,100,100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135,135,135)\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255,255,255);\n"
"    background-color: rgb(0,0,246)\n"
"}")
        self.checkBox_saveuser.setObjectName("checkBox_saveuser")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 190, 281, 51))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    background-color: rgb(50,50,50);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(177,209,250);\n"
"    border: 2px solid rgb(177, 185, 249);\n"
"    color: rgb(0, 0, 127);    \n"
"}\n"
"")
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.login)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("border: rgba(0,0,246,100)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.login)
        self.verticalLayout.addWidget(self.context)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Credito = QtWidgets.QLabel(self.bottom)
        self.label_Credito.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Credito.setObjectName("label_Credito")
        self.verticalLayout_3.addWidget(self.label_Credito)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_erro.setText(_translate("MainWindow", "error"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "USER"))
        self.lineEdit_user_2.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.checkBox_saveuser.setText(_translate("MainWindow", "Save user"))
        self.pushButton_login.setText(_translate("MainWindow", "Entrar"))
        self.label_Credito.setText(_translate("MainWindow", "Created by: RPA - Grupo Casas Bahia"))
import views.files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
